spring.application.name=CodeCoach

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/codecoach
spring.datasource.username=root
spring.datasource.password=bayush1209

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Gemini AI
gemini.api.key=${GEMINI_API_KEY}